[#7] [Backend] As a user, I can receive and verify an verification e-mail
nimblehq/ic-rails-huey-toby pull request #49
Opened 2023-07-11 10:09 UTC by Tuubz

Close #7

## What happened 👀

- Send verification e-mail after sign-up (with [letter_opener](https://github.com/ryanb/letter_opener) for development, otherwise with [mail-gun](https://github.com/mailgun/mailgun-ruby))
- Require that the e-mail has been verified before the user can sign in (with the help of `user.confirmed?`)
- Navigate to root when the confirmation link has been clicked

## Insight 📝

I had to add `include ActionController::Flash` in `ConfirmationsController` in order for the test to succeed 💭 

Seems like Devise is expecting this when the user is being redirected after confirmation 🤔 

**Note**: Since we don't have `staging.rb`, it will fallback to `production.rb`

## Proof Of Work 📹

**DEVELOPMENT (letter-opener):**

https://github.com/nimblehq/ic-rails-huey-toby/assets/18277915/98562eab-b988-4697-9c55-8a5577e0fe42

**STAGING/PRODUCTION (mail-gun):**

https://github.com/nimblehq/ic-rails-huey-toby/assets/18277915/79d49452-3422-4431-8a1e-206780eaa088

2023-07-11 10:19 UTC, hoangnguyen92dn commented
@Tuubz This PR should belongs to #7 🙈

2023-07-11 10:58 UTC, Tuubz commented
@hoangnguyen92dn Hahah, sorryyy. Updated ✅

2023-07-12 06:06 UTC, olivierobert approved these changes

2023-07-14 05:19 UTC, Tuubz commented
@hoangnguyen92dn @hoangmirs Resolved conflicts 🚀

2023-07-14 08:38 UTC, hoangnguyen92dn reviewed
I am just curious that we don't need to setup email sender to send email to user's mailbox? 🤔

2023-07-14 08:58 UTC, Tuubz commented
> I am just curious that we don't need to setup email sender to send email to user's mailbox? 🤔

You mean sending a real e-mail (for staging/production), right? Good question, I didn't thank about 💭

2023-07-14 09:07 UTC, Tuubz commented
Sorry guys, I missed this requirement 🙈 I'll put this PR on draft for now and start working on it 🙏

2023-07-17 08:19 UTC, hoangnguyen92dn approved these changes
@Tuubz From the PoW, the confirmation email should be redirected user to staging/production environment url instead of `localhost:3000`, so please don't forget to update the configs on heroku 😄

2023-07-17 08:20 UTC, Tuubz commented
@hoangnguyen92dn I forgot to mention:

- I added the environment variables to staging/production 👍 
- For testing, I only changed the values of `development.rb` to test it locally

2023-07-18 02:31 UTC, olivierobert requested changes

2023-07-18 02:31 UTC, olivierobert commented on Gemfile
> +  gem 'mailgun-ruby' # Contains methods for easily interacting with the Mailgun API
This should not be in the dev and test environments group only 🙈 This gem would not be installed in the prod environment. It should be moved in the block for `backend` (starting at line 4)

2023-07-18 03:10 UTC, hoangmirs commented on app/controllers/api/v1/users/sessions_controller.rb
> +            detail: [I18n.t('devise.failure.invalid', authentication_keys: :email)],
Sorry, maybe I missed it, but why did we use the array here?

2023-07-18 03:10 UTC, hoangmirs commented on spec/requests/sessions_controller_spec.rb
> +        expect(JSON.parse(response.body)['errors'][0]['detail']).to include(I18n.t('devise.failure.invalid', authentication_keys: :email))
The detail attribute should be a regular text following `JSON:API` spec:
> a human-readable explanation specific to this occurrence of the problem

And the test can be rewritten as:
```suggestion
        expect(JSON.parse(response.body)['errors'][0]['detail']).to eq(I18n.t('devise.failure.invalid', authentication_keys: :email))
```

2023-07-18 03:48 UTC, olivierobert approved these changes

2023-07-18 07:31 UTC, hoangmirs approved these changes

2023-07-18 07:31 UTC, hoangmirs approved these changes

2023-07-18 07:31 UTC, merged