[#1] Generate project from rails-templates
nimblehq/ic-rails-huey-toby pull request #5
Opened 2023-05-24 04:11 UTC by hoangnguyen92dn

- Close #1

## What happened 👀

Generate the project from [rails-templates](https://github.com/nimblehq/rails-templates)

## Insight 📝

- Add Github secrets to publish the wiki
- Update PR template
- Update deployment workflow branches:
  - Rename `development` -> `develop`
  - Remove `master` branch

*Notice:* CI/CD will be updated on:
- https://github.com/nimblehq/ic-rails-huey-toby/issues/2
- https://github.com/nimblehq/ic-rails-huey-toby/issues/3

## Proof Of Work 📹

- Start Docker
- Execute: `make dev`

![image](https://github.com/nimblehq/ic-rails-huey-toby/assets/6950766/23923172-822b-4943-b316-f05226a3d4b8)

2023-05-25 10:44 UTC, olivierobert requested changes

2023-05-25 10:44 UTC, olivierobert commented on .github/workflows/test.yml
> +      - name: Run unit tests
That can besimplified to run all tests:

```suggestion
      - name: Run tests
```

2023-05-26 03:51 UTC, hoangnguyen92dn commented on .github/workflows/test.yml
> +  system_tests:
@hoangmirs It's understandable if we combine the step to reduce the time of pulling the image. But I think we should keep it separated for each step, it's cleaner and easier to follow up on each step. cc @Tuubz

2023-05-26 04:02 UTC, hoangnguyen92dn commented on .github/wiki/Getting-Started.md
> +make dev
@hoangmirs I think we could consider to update the `rails-template` 👍

2023-05-26 04:09 UTC, hoangnguyen92dn commented on .github/workflows/test.yml
> +  system_tests:
Updated [c928293](https://github.com/nimblehq/ic-rails-huey-toby/pull/5/commits/c928293781b6d60a65ecf3e766405d0c680a5777)

2023-05-26 04:10 UTC, hoangnguyen92dn commented on .github/CODEOWNERS
> +* @hoangnguyen92dn @hoangmirs @olivierobert
Updated [9f3a0d9](https://github.com/nimblehq/ic-rails-huey-toby/pull/5/commits/9f3a0d9ee690cb9607956ff94f8fc95759c2ce16)

2023-05-26 04:10 UTC, hoangnguyen92dn commented on .github/PULL_REQUEST_TEMPLATE/RELEASE_TEMPLATE.md
> +or link to the release on the project management tool e.g. https://app.shortcut.com/nimblehq/label/12345
Updated [39bc5ca](https://github.com/nimblehq/ic-rails-huey-toby/pull/5/commits/39bc5ca8794f63314c9c40960b28c4e83a6bd6ce)

2023-05-26 04:11 UTC, hoangnguyen92dn commented on .github/wiki/Getting-Started.md
> +make dev
Updated [b81f24d](https://github.com/nimblehq/ic-rails-huey-toby/pull/5/commits/b81f24dfe9c316135a7ac6d7a695cf6ab1b2c268)

2023-05-26 04:11 UTC, hoangnguyen92dn commented on .github/workflows/test_production_build.yml
> +      - master
Updated [01515c7](https://github.com/nimblehq/ic-rails-huey-toby/pull/5/commits/01515c7f63cc073ae64d37ecd8f05210f3317305)

2023-05-26 04:11 UTC, hoangnguyen92dn commented on Makefile
> +	yarn install
Updated [c0e5c22](https://github.com/nimblehq/ic-rails-huey-toby/pull/5/commits/c0e5c22a05d73b13cad58dd793db5d58a525e1f9)

2023-05-26 04:16 UTC, hoangmirs commented on .github/wiki/Getting-Started.md
> +make dev
Feel free to create issues in the `rails-templates` so that the team can know and update it 💪

2023-05-26 05:31 UTC, olivierobert approved these changes

2023-05-26 05:45 UTC, hoangmirs approved these changes

2023-05-26 05:45 UTC, hoangmirs commented on .github/PULL_REQUEST_TEMPLATE/RELEASE_TEMPLATE.md
> +Link to the milestone on Github e.g. https://github.com/nimblehq/ic-rails-huey-toby/milestone/41?closed=1
I think we just need the URL here:
```suggestion
https://github.com/nimblehq/ic-rails-huey-toby/milestone/{milestone-id}?closed=1
```

2023-05-29 02:46 UTC, Tuubz approved these changes
💪

2023-05-29 02:47 UTC, merged